trigger:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"
    mac:
      imageName: "macos-10.13"
    windows:
      imageName: "vs2017-win2016"
      doPack: true
  maxParallel: 3

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    verbosityRestore: Minimal
    configuration: $(buildConfiguration)
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    configuration: $(buildConfiguration)
- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    configuration: $(buildConfiguration)
    nobuild: true
- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'pack'
    configuration: $(buildConfiguration)
    packagesToPack: '**/*.csproj'
    packDirectory: $(Build.ArtifactStagingDirectory)
    includesymbols: true
    includesource: true
    versioningScheme: 'off'
    verbosityPack: 'Minimal'
    verbosityRestore: 'Minimal'